import type { Pattern } from '../../types/pattern'
import { createPerlinFieldRenderer } from './renderer'

export const perlinField: Pattern = {
  id: 'perlin-field',
  title: 'Perlin / Simplex Noise',
  category: 'Noise / Flow',
  blurb:
    "Ken Perlin's 1985 gradient noise (and the 2001 simplex variant) — the workhorse of procedural generation. Layered octaves of bandlimited noise produce 'natural-looking' randomness used in every modern game.",
  params: [
    {
      type: 'number',
      name: 'scale',
      label: 'scale (px / unit)',
      description: 'Higher = larger, slower features. Lower = finer.',
      min: 30,
      max: 400,
      step: 5,
      default: 120,
    },
    {
      type: 'number',
      name: 'octaves',
      label: 'octaves',
      description: 'Number of noise layers summed together.',
      min: 1,
      max: 8,
      step: 1,
      default: 5,
    },
    {
      type: 'number',
      name: 'persistence',
      label: 'persistence',
      description: 'Amplitude ratio between octaves. < 1 = higher frequencies fade.',
      min: 0.1,
      max: 0.95,
      step: 0.05,
      default: 0.5,
    },
    {
      type: 'number',
      name: 'lacunarity',
      label: 'lacunarity',
      description: 'Frequency ratio between octaves. > 1 = higher octaves are finer.',
      min: 1.2,
      max: 4,
      step: 0.1,
      default: 2,
    },
    {
      type: 'number',
      name: 'animSpeed',
      label: 'animation speed (z drift)',
      min: 0,
      max: 5,
      step: 0.1,
      default: 0.6,
    },
    {
      type: 'number',
      name: 'seed',
      label: 'seed',
      min: 1,
      max: 9999,
      step: 1,
      default: 1337,
    },
    {
      type: 'select',
      name: 'palette',
      label: 'palette',
      options: [
        { value: 'grayscale', label: 'Grayscale' },
        { value: 'terrain', label: 'Terrain' },
        { value: 'fire', label: 'Fire' },
        { value: 'plasma', label: 'Plasma' },
      ],
      default: 'terrain',
    },
    {
      type: 'boolean',
      name: 'contour',
      label: 'isolines',
      default: false,
    },
  ],
  createRenderer: createPerlinFieldRenderer,
  explainer: () => import('./Explainer'),
  drawEvery: 2,
}
