import { TeX } from '../../components/Math'

export default function Explainer() {
  return (
    <>
      <p>
        Michael Barnsley's 1988 fern is generated by repeatedly applying one of four affine
        transformations to the current point, picking each transformation with a fixed
        probability:
      </p>
      <TeX
        block
        tex="\begin{pmatrix}x_{n+1}\\y_{n+1}\end{pmatrix} = \begin{pmatrix}a&b\\c&d\end{pmatrix}\begin{pmatrix}x_n\\y_n\end{pmatrix} + \begin{pmatrix}e\\f\end{pmatrix}"
      />
      <p>The four transformations and their probabilities encode the parts of the fern:</p>
      <ul>
        <li>
          <strong>1%</strong> — flatten to the stem.
        </li>
        <li>
          <strong>85%</strong> — slight rotation + slight shrink (extends the next leaflet).
        </li>
        <li>
          <strong>7%</strong> — rotate left + scale (left-side leaflet).
        </li>
        <li>
          <strong>7%</strong> — rotate right + scale (right-side leaflet).
        </li>
      </ul>
      <p>
        That four short matrix-vector ops, run a few hundred thousand times, produce a
        recognisable fern is one of the great surprises of fractal geometry. Each species preset
        here changes only the matrix coefficients.
      </p>
    </>
  )
}
