import type { Pattern } from '../../types/pattern'
import { createBoidsRenderer } from './renderer'

export const boids: Pattern = {
  id: 'boids',
  title: 'Boids Flocking',
  category: 'Growth',
  blurb:
    'Craig Reynolds 1987. Each bird follows three local rules: separate, align, cohere. No leader, no global plan — yet starlings, sardines, and bees flock convincingly.',
  params: [
    {
      type: 'number',
      name: 'count',
      label: 'flock size',
      min: 50,
      max: 400,
      step: 10,
      default: 200,
    },
    {
      type: 'number',
      name: 'separation',
      label: 'separation',
      description: 'How strongly boids avoid crowding.',
      min: 0,
      max: 200,
      step: 5,
      default: 80,
    },
    {
      type: 'number',
      name: 'alignment',
      label: 'alignment',
      description: 'How strongly boids match neighbours\' velocity.',
      min: 0,
      max: 5,
      step: 0.05,
      default: 1.4,
    },
    {
      type: 'number',
      name: 'cohesion',
      label: 'cohesion',
      description: 'How strongly boids steer toward the local center of mass.',
      min: 0,
      max: 5,
      step: 0.05,
      default: 1.0,
    },
    {
      type: 'number',
      name: 'sepRadius',
      label: 'separation radius',
      min: 5,
      max: 50,
      step: 1,
      default: 20,
    },
    {
      type: 'number',
      name: 'visRadius',
      label: 'vision radius',
      min: 20,
      max: 200,
      step: 5,
      default: 60,
    },
    {
      type: 'number',
      name: 'maxSpeed',
      label: 'max speed',
      min: 1,
      max: 6,
      step: 0.1,
      default: 2.5,
    },
  ],
  createRenderer: createBoidsRenderer,
  explainer: () => import('./Explainer'),
}
